[package]
name = "esm-compiler"
version = "0.0.6"
description = "A WASM module to compiler code for esm-worker."
repository = "https://github.com/alephjs/aleph.js"
authors = ["The Aleph.js authors"]
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
anyhow = "1.0.51" 
indexmap = "1.7.0"
path-slash = "0.1.4" 
regex = "1.5.4"
relative-path = "1.5.0"
serde = { version = "1.0.130", features = ["derive"] }
url = "2.2.2"

# swc
# docs: https://swc.rs
# crate: https://crates.io/search?q=swc
swc_atoms = "0.2.9"
swc_common = { version = "0.14.7", features = ["sourcemap"] }
swc_ecma_ast = "0.58.1"
swc_ecma_transforms_proposal = "0.59.0"
swc_ecma_transforms_typescript = "0.62.0"
swc_ecma_utils = "0.52.5"
swc_ecma_visit = "0.44.1"
swc_ecmascript = { version = "0.89.0", features = ["codegen", "parser", "react", "transforms", "visit"] }

# wasm-bindgen
# docs: https://rustwasm.github.io/docs/wasm-bindgen
wasm-bindgen = {version = "0.2.78", features = ["serde-serialize"] }
console_error_panic_hook = { version = "0.1.7", optional = true }

[profile.release]
# Tell `rustc` to optimize for speed and size
lto = true