[package]
name = "lol-html-wasm"
version = "0.3.1"
authors = ["Ivan Nikulin <inikulin@cloudflare.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.55"
lol_html = "0.3.0"
serde = { version = "1.0.130", features = ["derive"] }
serde-wasm-bindgen = "0.3.1"
wasm-bindgen = "0.2.78"
thiserror = "1.0.30"
encoding_rs = "0.8.29"

[profile.release]
# Tell `rustc` to optimize for speed and size
lto = true